[versions]
versionName = "1.0.0-beta2"

kotlinVersion = "1.9.24"
dokkaVersion = "1.8.20"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinVersion" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokkaVersion" }